### ISSUE TITLE
[server-wallet] Milestone 0

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2310]
There are three different pieces of "wallet logic" to work on:
1. The `Wallet` class, which exposes the wallet API
2. The "protocols", which decide what action (actions?) to take in a given situation.
3. The "`protocolEngine`", which the wallet class would use to run a protocol.

## Tasks

- [x] https://github.com/statechannels/monorepo/issues/2312: One person should write the "app" protocol, which enables the `updateChannel` API call.
- [ ] https://github.com/statechannels/monorepo/issues/2314: Another person can independently write the "direct funding" protocol, if we have the cycles.
- [ ] https://github.com/statechannels/monorepo/issues/2311: One person should work out how the "protocol engine" works + the wallet API implementation. (These two seem fairly coupled)
- [x] https://github.com/statechannels/monorepo/issues/2313: One person can focus on writing an integration test.

**Comment by andrewgordstewart** [comment]
stale
