### ISSUE TITLE
[nitro-protocol] Audit followup work

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#2905]
# Work
- [x] ~Protect against a "bad" destination: https://github.com/statechannels/statechannels/pull/2844~
- [x] Document precautions: #2915 
- [x] Check the chainId: https://github.com/statechannels/statechannels/pull/2914
- [x] Catch external destination collisions https://github.com/statechannels/statechannels/pull/2924
- [x] Require nonzero return value from ecrecover https://github.com/statechannels/statechannels/pull/2925
- [x] Better `bytesEqual` check https://github.com/statechannels/the-graph/pull/369
- [x]  add claim method to AssetHolder #2932
- [x] perf: break out of loops a bit earlier #2926
- [x] convert public methods to external #2933 
- [x] Use consistent naming for interfaces #2954
- [x] reuse solidity code more #2980 
- [x] remove unnecessary `abi.encode` during `hashOutcome` #2955 
- [x] resolve all conversations in the [long-form response](https://www.notion.so/Resolutions-fe995c3eb6e6464d8af137f9b0edc2ad)

**Comment by geoknee** [comment]
https://statechannels.slack.com/files/UACLTBS3G/F01FF24U2DN/Audit_recommendations.txt

**Comment by geoknee** [comment]
Long form response https://www.notion.so/Resolutions-fe995c3eb6e6464d8af137f9b0edc2ad to audit report.

**Comment by andrewgordstewart** [comment]
@geoknee I've left my comments in the resolutions doc. Can you address them today?
