### ISSUE TITLE
[audit] 6.1, 6.3, 6.4 Fix validTransition

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3035]
[Explaination required] See https://github.com/statechannels/statechannels/issues/2738 for some context.

- [x] add a check for channelNonce inside validateTransition #3039 
- [x] incorporate turnNum check inside `_requireExtraImplicitChecks(fromState, toState)` ;#3041
- [x] introduce `requireValidProtocolTransition` typescript emulator for `ForceMove.sol` function (with cross-language test) #3041 
- [ ] clearly separate:
      - transition validation (protocol, app); 
      - inference of a support proof of a state in the `store`; 
      - garbage collection / early discard of unwanted states during `pushMessage`.

**Comment by geoknee** [comment]
> 6.1 server-wallet - validateTransition fails to return on turn number check failed Major
6.3 sever-wallet - validateTransition is missing a check for channelNonce Major
6.4 server-wallet - validateTransition checks differ from ForceMove._requireValidTransition Major
I think we'll take the recommendation to call out to the NitroAdjudicator contract for the `validTransition` call.
This would be a fairly simple refactor, but it may have throughput & latency consequences.
If we do it, it will tick all of these three

**Comment by geoknee** [comment]
Some observations about calling out to the NitroAdjudicator contract:
- it hooks an external API (e.g. infura) into our critical path. Even if it is usually fast and reliable, it may not always be and we can't control that. If there are other possibilities, such as running the EVM code in our client we should explore those first. We already do this but in a way that is easy to become (and actually is) out of sync.
- the on-chain `validTransition` function works in tandem with other on-chain functions to ensure a state is supported. Some of the checks are done implicitly as a part of the signature validation. So we either need to a) rewrite some of the implicit checks in our client code b) refactor the on chain code to do some more (redundant) explicit checks at a higher gas cost or c) refactor the client code to perform the signature validation and transition validation together in the same implicit manner. Option a) might be workable especially if we protect ourselves with a comprehensive test suite.

**Comment by geoknee** [comment]
Pinching off the remaining issue into #3137
