### ISSUE TITLE
Implement create2 version of Nitro protocol

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#3415]
Reimplement Nitro contracts such that the happy path gas costs are as low as possible (using a create2/proxy system).

As per RFC9 https://www.notion.so/statechannels/RFC-9-Implement-a-create2-version-of-Nitro-e0f89044eed546c29700f5695ff80dff

**Comment by geoknee** [comment]
Specific goals: 


- [ ] Help @NiloCK get up to speed / comfortable with writing Solidity code, deploying contracts and testing them
- [ ]  Implement a fully-featured, create2 version of Nitro protocol
- [ ]  Extend test coverage of the new implementation so that it has parity with our current test suite
- [ ] Measure gas costs for the new implementation
- [ ] Execute a cross-chain swap using the new implementation in our [cross-chain-swaps repo](https://github.com/statechannels/cross-chain-swaps) (and understand the extent of the gas savings :fingers-crossed:
