### ISSUE TITLE
[channel-client] Implement a public-facing API for dapps to use

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/statechannels#398]
This issue will track the creation of a `ChannelClient`.

The API is comprised of the following actions.

1. If someone calls `openChannel`, create the corresponding `opening` state (using fake data where required) and:
    1. Trigger a `channelUpdated(opening)` 
    2. Trigger a `sendMessage(opponent, channelProposed(opening))`
2. If someone calls `messageReceived(someEvent)`, then
    1. Trigger `someEvent`
3. If someone calls `joinChannel`
    1. Trigger a `channelUpdated`
    2. Trigger a `sendMessage(opponent, channelUpdated)`
4. If someone calls `updateState()`
    1. Trigger a `channelUpdated`
    2. Trigger a `sendMessage(opponent, channelUpdated)`

The API was expanded via #384 and #427.

### Tasks

- [x] Implement `openChannel`
- [x] Implement `sendMessage`
- [x] Implement event transmission for `channelUpdated`
- [ ] Implement error types
- [ ] Simulate data flow

Implementation and related discussions are happening in #402.

**Comment by snario** [comment]
This is now being worked on by @andrewgordstewart (see #1933 for example)
